### ISSUE TITLE
Not an issue, it just sucks this is dead

### ISSUE THREAD

**Issue by Sonico98** [innocenat/typingmania#1] opened 2020-04-01 03:44 UTC
Amazing game, would've loved if this got more attention :(

**Comment by innocenat** [comment] 2020-04-01 04:25
Sorry about that.

I think the current code still works as intended, I think. But a lot of new technology has become mainstream since then and a rewrite would be better at this point. I am working on them, but I don't have much free time nowadays.

**Comment by Sonico98** [comment] 2020-04-11 21:49
> Sorry about that.
> 
> I think the current code still works as intended, I think. But a lot of new technology has become mainstream since then and a rewrite would be better at this point. I am working on them, but I don't have much free time nowadays.

Don't say sorry! It's not your fault. Good luck with the rewrite

**Comment by innocenat** [comment] 2021-03-12 10:54
Hello.

I just pushed the rewrite version into new branch (which I made default). The documentation and tooling around it is still lacking and I am still working on it.

The new main feature is that it now supports video, either locally, or embeded via YouTube. 

Keeping this issue open until I finished all documentation and tooling.

Example screen playing LiSA's Homura via YouTube: https://i.imgur.com/1U142Ek.jpg

**Comment by innocenat** [comment] 2021-05-20 06:30
I am closing this with the release of TypingMania NEO 1.0.0.

**Closed as completed by innocenat** 2021-05-20 06:30 UTC
